backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "gallery"
    label: "Gallery"
    file: "gallery.json"
    fields:
      - label: "Images"
        name: "images"
        widget: list
        fields:
          - label: "Image"
            name: "image"
            widget: image
          - label: "Title"
            name: "title"
            widget: string
          - label: "Category"
            name: "category"
            widget: select
            options:
              - Rings
              - Necklaces
              - Custom
              - CAD
